export const ActionTypes = {
  INITIAL_TASK_STATE: 'INITIAL_TASK_STATE',

  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',

  TASK_COMPLETE_REQUEST: 'TASK_COMPLETE_REQUEST',
  TASK_COMPLETE_SUCCESS: 'TASK_COMPLETE_SUCCESS',
  TASK_COMPLETE_FAILURE: 'TASK_COMPLETE_FAILURE',
}
