export const ActionTypes = {
  INITIAL_TASK_STATE_REQUEST: 'INITIAL_TASK_STATE_REQUEST',
  INITIAL_TASK_STATE_SUCCESS: 'INITIAL_TASK_STATE_SUCCESS',

  INITIAL_COMPLETE_TASK_STATE: 'INITIAL_COMPLETE_TASK_STATE',

  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
}
