export const ActionTypes = {
  INITIAL_PROJECT_STATE_REQUEST: 'INITIAL_PROJECT_STATE_REQUEST',
  INITIAL_PROJECT_STATE_SUCCESS: 'INITIAL_PROJECT_STATE_SUCCESS',

  ADD_PROJECT_REQUEST: 'ADD_PROJECT_REQUEST',
  ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',

  UPDATE_PROJECT_REQUEST: 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
}
