export const ActionTypes = {
  INITIAL_PROJECT_STATE: 'INITIAL_PROJECT_STATE',
  ADD_PROJECT_REQUEST: 'ADD_PROJECT_REQUEST',
  ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
  ADD_PROJECT_FAILURE: 'ADD_PROJECT_FAILURE',
}
