export const ActionTypes = {
  INITIAL_POMO_STATE: 'INITIAL_POMO_STATE',

  UPDATE_POMO_REQUEST: 'UPDATE_POMO_REQUEST',
  UPDATE_POMO_SUCCESS: 'UPDATE_POMO_SUCCESS',
  UPDATE_POMO_FAILURE: 'UPDATE_POMO_FAILURE',
}
