export const ActionTypes = {
  INITIAL_COMPLETE_TASK_STATE: 'INITIAL_COMPLETE_TASK_STATE',

  TASK_COMPLETE_REQUEST: 'TASK_COMPLETE_REQUEST',
  TASK_COMPLETE_SUCCESS: 'TASK_COMPLETE_SUCCESS',
  TASK_COMPLETE_FAILURE: 'TASK_COMPLETE_FAILURE',

  TASK_RECOVERY_REQUEST: 'TASK_RECOVERY_REQUEST',
  TASK_RECOVERY_SUCCESS: 'TASK_RECOVERY_SUCCESS',
  TASK_RECOVERY_FAILURE: 'TASK_RECOVERY_FAILURE',
}
